# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Introduction to Computer Graphics
subtitle: "CS3451, Fall 2019"
description: Introduction to Computer Graphics
email: blair@gatech.edu
twitter_username: blairmacintyre
github_username: blairmacintyre
minimal_mistakes_skin: dark
search: true
repository: cs3451/cs3451.github.io
breadcrumbs: true
follow_label: "Follow Blair MacIntyre"
name: "Blair MacIntyre, Georgia Tech"

logo: /assets/images/puppy-logo-120x120.png # 120x120 px default image used for Twitter summary card
teaser: /assets/images/shark-table-360x240.png # 400x250 px default teaser image used in image archive grid
url: https://cs3451.github.io
#url: http://localhost:4000

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
#theme: minimal-mistakes-jekyll
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/New_York
highlighter: rouge

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# author:
#   name   : "Blair MacIntyre"
#   avatar : "/assets/images/bio-blair.jpg"
#   bio    : "Course Instructor<br>Professor, School of Interactive Computing<br>Principal Research Scientist, Mozilla"
#   links:
#     - label: "Website"
#       icon: "fas fa-fw fa-link"
#       url: "https://blairmacintyre.me"
#     - label: "GitHub"
#       icon: "fab fa-fw fa-github"
#       url: "https://github.com/blairmacintyre"

footer:
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://cs3451.github.io"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/cs3451/"

comments:
  provider: "utterances"
  utterances:
    theme: "github-dark"
    issue_term: "cs3451/cs3451.github.io"

defaults:
  - values:
      author_profile: false

  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      comments: true
      share: false
      related: true
      sidebar:
      - title: Time and Place
        text: "TTh, 12:00 – 1:15, Klaus 1443"
        nav: "side"
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      share: false
      comments: true
      classes: wide
      sidebar:
      - title: Time and Place
        text: "TTh, 12:00 – 1:15, Klaus 1443"
        nav: "side"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
